pipeline {
    agent {
        label 'slave1'
    }
    parameters {
        booleanParam(name: 'CHECKOUT', defaultValue: true, description: 'Toggle this value to checkout')
        booleanParam(name: 'BUILD', defaultValue: true, description: 'Toggle this value to build')
        booleanParam(name: 'TEST', defaultValue: true, description: 'Toggle this value to test')
        booleanParam(name: 'DEPLOY', defaultValue: true, description: 'Toggle this value to deploy')
        string(name: 'PARAM_STRING', defaultValue: 'input_param', description: 'This is a string parameter')
    }
    environment {
        GLOBAL = 'This is a global variable'
    }
    triggers {
        cron('* */23 * * *')
    }
    stages {
        stage('CHECKOUT') {
            when {
                expression {
                    params.CHECKOUT == true
                }
            }
            steps {
                script {
                    checkout([$class: 'GitSCM', 
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [[url: 'https://github.com/chinmaigowda/mvn1.git',
                    credentialsId: 'GitHub']]])
                }
            }
        }
        stage('BUILD') {
            when {
                expression {
                    params.BUILD == true
                }
            }
            steps {
                sh '''
                    set +x
                    echo "$GLOBAL"
                    echo "${PARAM_STRING}"
                '''
            }
        }
        stage('TEST') {
            when {
                expression {
                    params.TEST == true
                }
            }
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                    echo "$LOCAL"
                '''
            }
        }
        stage('DEPLOY') {
            when {
                expression {
                    params.DEPLOY == true
                }
            }
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                '''
            }
        }
    }    
}
