pipeline {
    agent {
        label 'slave1'
    }
    environment {
        GLOBAL = 'This is a global variable'
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                    echo "$GLOBAL"
                '''
            }
        }
    
        stage('Build1') {
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                '''
            }
        }
        stage('Test1') {
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                '''
            }
        }
    }    
}
